sudo: false

os:
  - osx
  - linux

env:
  matrix:
    - ELM_VERSION=0.19 ELM_TEST_VERSION=elm0.19.0 TARGET_NODE_VERSION=node

install:
  - nvm install $TARGET_NODE_VERSION
  - nvm use $TARGET_NODE_VERSION
  - node --version
  - npm --version
  - npm install -g elm@$ELM_VERSION
  - npm install -g elm-test@$ELM_TEST_VERSION
  - npm install -g elm-verify-examples
  - elm --version
  - elm-test --version
  - elm-verify-examples --version

script:
  - ./run_tests.sh
